### ISSUE TITLE
Bot Key error

### ISSUE THREAD

**Issue by sultan-sheriff** [automagica/automagica#113]
File "C:\Users\Dell\Desktop\testing_for_automagica\venv\lib\site-packages\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Dell\Desktop\testing_for_automagica\venv\lib\site-packages\automagica\activities.py", line 8490, in find_text_on_screen_ocr
    api_key = str(local_data['bot_secret'])  # Your API key
KeyError: 'bot_secret'
(venv) PS C:\Users\Dell\Desktop\testing_for_automagica> automagica -f .\ocr_testing.py
Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dell\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dell\Desktop\testing_for_automagica\venv\Scripts\automagica.exe\__main__.py", line 7, in <module>
  File "c:\users\dell\desktop\testing_for_automagica\venv\lib\site-packages\automagica\cli.py", line 652, in main
    app = Automagica()
  File "c:\users\dell\desktop\testing_for_automagica\venv\lib\site-packages\automagica\cli.py", line 139, in __init__
    exec(script, globals())
  File "<string>", line 5, in <module>
  File "c:\users\dell\desktop\testing_for_automagica\venv\lib\site-packages\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "c:\users\dell\desktop\testing_for_automagica\venv\lib\site-packages\automagica\activities.py", line 8490, in find_text_on_screen_ocr
    api_key = str(local_data['bot_secret'])  # Your API key
KeyError: 'bot_secret'

@audieleon @ygxiao  @tvturnhout @0xflotus @rtroncosogar 
can u guys help solving this problem    .Every time when i work on OCR it gices me  the Above error

**Comment by sultan-sheriff** [comment]
@ygxiao @audieleon @tvturnhout @rtroncosogar  guys please help me on the above mentioned error

**Comment by koenvaneijk** [comment]
Please follow these instructions:
https://github.com/automagica/automagica/issues/99

**Comment by koenvaneijk** [comment]
To access the OCR service, you need to register for the Automagica Portal.

**Comment by sultan-sheriff** [comment]
Hi After registering also i am getting the same error @koenvaneijk  @ygxiao @audieleon @tvturnhout
