### ISSUE TITLE
automagica.activities.find_text_on_screen_ocr is not working 

### ISSUE THREAD

**Issue by pradeep08** [automagica/automagica#116]
When i try to search a text on the screen using automagica.activities.find_text_on_screen_ocr(testfile), i had encountered, FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\userid\automagica.json'. Later i have created a empty JSON file in the path. Then the following error is being observed
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\automagica\activities.py", line 8489, in find_text_on_screen_ocr
    local_data = json.load(json_file)
  File "C:\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**Comment by kathawala** [comment]
You need an API key to do those actions.

I've made a pull request with better error handling to make this more clear ( #119 )

**Comment by pradeep08** [comment]
@kathawala  How to obtain API Key?

**Comment by kathawala** [comment]
You need to sign up on the automagica website, I'm working on a fork to allow ocr activities without API key, but no guarantees on that

**Comment by yongruning** [comment]
excuse me,Are the OR API any usage times per day?

**Comment by yongruning** [comment]
@tvturnhout  excuse me,Will the OCR API limit the number of usage times  per day?

**Comment by yongruning** [comment]
excuse me,how do I get the API key after registration，will the OCR API limit the number of usage times  per day

**Comment by valerietram88** [comment]
> You need to sign up on the automagica website, I'm working on a fork to allow ocr activities without API key, but no guarantees on that

Have you finished your work?

**Comment by koenvaneijk** [comment]
This is currently not on our roadmap for Automagica, however we are looking at the possibility of BYOOCR (Bring Your Own OCR).
