### ISSUE TITLE
How to SUCCESSFULLY use automagica from python?

### ISSUE THREAD

**Issue by fengnex** [automagica/automagica#126]
1. pip install automagica --upgrade
2. execute the following code snippets:
from automagica import *
txt=activities.extract_text_ocr("D:/devea/open-verify/file1.png")
3. Got the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\ProgramData\Python37\lib\site-packages\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "F:\ProgramData\Python37\lib\site-packages\automagica\activities.py", line 8851, in extract_text_ocr
    with open(config_path) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\automagica.json'

4. Creating an empty file named as automagica.json under the required directroy and then the following error occured:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\ProgramData\Python37\lib\site-packages\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "F:\ProgramData\Python37\lib\site-packages\automagica\activities.py", line 8852, in extract_text_ocr
    local_data = json.load(json_file)
  File "F:\ProgramData\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "F:\ProgramData\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "F:\ProgramData\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\ProgramData\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

MY QUESTION: 
Is it possible to use automagica from python like the above steps since it's opensourced? How to use it if so?

**Comment by kathawala** [comment]
The code in #136 will allow you to run the script. But currently, you need an Automagica Portal key to use OCR functions.

**Comment by koenvaneijk** [comment]
Please read the [documentation](https://automagica.readthedocs.io) and more specifically [here](https://automagica.readthedocs.io/getting_started.html#installing-on-windows). The OCR service is only available for [Automagica Portal](https://portal.automagica.com) users.
